name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    timeout-minutes: 30
    strategy:
      matrix:
        rust-version: ["1.65.0"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          rustup component add rustfmt
          rustup component add clippy
        name: Install Rust components
      - run: rustc --version
        name: Print Rust information
      - run: cargo fmt --all -- --check
        name: Verify Rust code format
      - run: cargo clippy -- -D warnings -A unknown-lints
        name: Verify Rust code linting
      - run: |
          cargo login $CRATES_TOKEN
          cargo publish --no-verify
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        name: Deploy packages to Cargo
  build-wasm:
    name: Build WASM
    timeout-minutes: 30
    strategy:
      matrix:
        rust-version: ["1.65.0"]
        node-version: ["16"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          rustup component add rustfmt
          rustup component add clippy
        name: Install Rust components
      - run: rustc --version
        name: Print Rust information
      - run: cargo fmt --all -- --check
        name: Verify Rust code format
      - run: cargo clippy -- -D warnings -A unknown-lints
        name: Verify Rust code linting
      - run: cargo install wasm-pack
        name: Install wasm-pack
      - run: wasm-pack build --release --target=web --out-dir=frontends/web/lib -- --features wasm
        name: Build WASM Web binary
      - uses: actions/setup-node@v1
        with:
          node-version: matrix-node-version
        name: Install Node.js
      - run: cd frontends/web && npm install && npm run build && npm run lint
        name: Build and lint Web code
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          cd frontends/web/lib && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Deploy packages to NPM
